apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    app: tomcat-app
spec:
  type: NodePort
  selector:
    app: tomcat-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30888
